language: python
dist: xenial
sudo: true
python:
  - 3.8
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
    - pipenv run flake8 .
    - pipenv run pytest --cov=libpythonpro
after_success:
  - pipenv run codecov

